### ISSUE TITLE
SuperMic MPI4py execution via custom OpenMPI installation

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#1]
I create the following script and run it on SuperMic using a python module offered by SUpermic's admins and the python environment I installed based on your instructions. The script is:
```python
#!/usr/bin/env python
import os
from mpi4py import MPI

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()

print("I am rank %d from %d procs, running on %s"%(rank,size,os.uname()[1]))
```
Essentially it prints the rank of a process, the world size and the hostname of the node the process run.

When I used the python module provided by SuperMic I got:
```bash
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ module load python/2.7.10-mkl-mic
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ mpirun -n 40 python test_mpi.py
I am rank 5 from 40 procs, running on smic067
I am rank 26 from 40 procs, running on smic068
I am rank 38 from 40 procs, running on smic068
I am rank 34 from 40 procs, running on smic068
I am rank 19 from 40 procs, running on smic067
I am rank 20 from 40 procs, running on smic068
I am rank 16 from 40 procs, running on smic067
I am rank 24 from 40 procs, running on smic068
I am rank 18 from 40 procs, running on smic067
I am rank 13 from 40 procs, running on smic067
I am rank 32 from 40 procs, running on smic068
I am rank 12 from 40 procs, running on smic067
I am rank 35 from 40 procs, running on smic068
I am rank 23 from 40 procs, running on smic068
I am rank 3 from 40 procs, running on smic067
I am rank 22 from 40 procs, running on smic068
I am rank 9 from 40 procs, running on smic067
I am rank 6 from 40 procs, running on smic067
I am rank 21 from 40 procs, running on smic068
I am rank 29 from 40 procs, running on smic068
I am rank 2 from 40 procs, running on smic067
I am rank 14 from 40 procs, running on smic067
I am rank 27 from 40 procs, running on smic068
I am rank 4 from 40 procs, running on smic067
I am rank 30 from 40 procs, running on smic068
I am rank 31 from 40 procs, running on smic068
I am rank 11 from 40 procs, running on smic067
I am rank 0 from 40 procs, running on smic067
I am rank 37 from 40 procs, running on smic068
I am rank 17 from 40 procs, running on smic067
I am rank 36 from 40 procs, running on smic068
I am rank 8 from 40 procs, running on smic067
I am rank 25 from 40 procs, running on smic068
I am rank 10 from 40 procs, running on smic067
I am rank 33 from 40 procs, running on smic068
I am rank 1 from 40 procs, running on smic067
I am rank 28 from 40 procs, running on smic068
I am rank 39 from 40 procs, running on smic068I am rank 7 from 40 procs, running on smic067

I am rank 15 from 40 procs, running on smic067
```

which is what I expected it to be.

But when I used our installation, I got:
```bash
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ module purge
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ module load gcc/4.9.0
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ module load openmpi_custom
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ module load hdf5_custom
[iparaske@smic067 MPI-RMSD-Parallel-IO]$
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ export PATH=/home/iparaske/miniconda3/bin:$PATH
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ export HDF5_MPI="ON"
[iparaske@smic067 MPI-RMSD-Parallel-IO]$
[iparaske@smic067 MPI-RMSD-Parallel-IO]$ source activate mpio
(mpio) [iparaske@smic067 MPI-RMSD-Parallel-IO]$
(mpio) [iparaske@smic067 MPI-RMSD-Parallel-IO]$ mpirun -n 40 python test_mpi.py
I am rank 16 from 40 procs, running on smic067
I am rank 17 from 40 procs, running on smic067
I am rank 18 from 40 procs, running on smic067
I am rank 19 from 40 procs, running on smic067
I am rank 22 from 40 procs, running on smic067
I am rank 24 from 40 procs, running on smic067
I am rank 25 from 40 procs, running on smic067
I am rank 28 from 40 procs, running on smic067
I am rank 29 from 40 procs, running on smic067
I am rank 30 from 40 procs, running on smic067
I am rank 31 from 40 procs, running on smic067
I am rank 33 from 40 procs, running on smic067
I am rank 34 from 40 procs, running on smic067
I am rank 37 from 40 procs, running on smic067
I am rank 38 from 40 procs, running on smic067
I am rank 0 from 40 procs, running on smic067
I am rank 1 from 40 procs, running on smic067
I am rank 2 from 40 procs, running on smic067
I am rank 3 from 40 procs, running on smic067
I am rank 4 from 40 procs, running on smic067
I am rank 5 from 40 procs, running on smic067
I am rank 11 from 40 procs, running on smic067
I am rank 12 from 40 procs, running on smic067
I am rank 13 from 40 procs, running on smic067
I am rank 15 from 40 procs, running on smic067
I am rank 7 from 40 procs, running on smic067
I am rank 8 from 40 procs, running on smic067
I am rank 9 from 40 procs, running on smic067
I am rank 36 from 40 procs, running on smic067
I am rank 21 from 40 procs, running on smic067
I am rank 6 from 40 procs, running on smic067
I am rank 32 from 40 procs, running on smic067
I am rank 35 from 40 procs, running on smic067
I am rank 10 from 40 procs, running on smic067
I am rank 20 from 40 procs, running on smic067
I am rank 26 from 40 procs, running on smic067
I am rank 39 from 40 procs, running on smic067
I am rank 27 from 40 procs, running on smic067
I am rank 23 from 40 procs, running on smic067
I am rank 14 from 40 procs, running on smic067
```

Clearly, the custom installation does not place the processes correctly. I will run a check with the placement command you provided to see what is going on.

**Comment by mkhoshle** [comment]
I think when I emailed you, I told you that when I login to compute nodes I see that some nodes are very busy while the rests are doing nothing which is because of rank distribution. What do you want to say here? What you are showing is expected and that is why you are not getting better performance. Change the rank distribution and you will get performance. If you want my submit script I can put it in our shared folder.

**Comment by iparask** [comment]
There are two issues that did not allow the execution to distribute correctly on SuperMic. Apparenlty, none of those had to do with the exact distribution of the processes.

First of all, SuperMic is a PBS cluster and not SLURM. That means that information about the node list and environment is a bit different compared to Comet and Bridges (both SLURM clusters).

Initially, I had to reinstall OpenMPI and include `--enable-orterun-prefix-by-default` flag during configuration. Secondly, I had to include the path and library path to my bashrc. It seems that `mpirun` did not see the correct configuration although I was passing `PATH` and `LD_LIBRARY_PATH` with the `-x` flag. I was told by the lead developer in the lab that `-x` option has to do with the workload and not with `mpirun` and suggested to include the path to the executable and libraries to my `.bashrc`. This is was the first issue.

The second issue was that `mpirun` did not see the host list correctly and assumed a single node. In order to distribute the processes correctly to the acquired nodes the host list had to provided manually.

Based on all this:
 1. The path should be setup in the `.bashrc` so that all nodes see the correct `mpirun` and the correct libraries, and
 2. The hostlist should be discovered by the user and passed to `mpirun`. 

So the command on SuperMic look like:
```
(mpio) [iparaske@smic025 MPI-RMSD-Parallel-IO]$ mpirun -x PATH -x LD_LIBRARY_PATH -host smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic025,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027,smic027 -np 40 python test_mpi.py
```
And the output is:
```
I am rank 33 from 40 procs, running on smic027.
I am rank 34 from 40 procs, running on smic027.
I am rank 35 from 40 procs, running on smic027.
I am rank 36 from 40 procs, running on smic027.
I am rank 37 from 40 procs, running on smic027.
I am rank 38 from 40 procs, running on smic027.
I am rank 39 from 40 procs, running on smic027.
I am rank 20 from 40 procs, running on smic027.
I am rank 21 from 40 procs, running on smic027.
I am rank 23 from 40 procs, running on smic027.
I am rank 24 from 40 procs, running on smic027.
I am rank 25 from 40 procs, running on smic027.
I am rank 26 from 40 procs, running on smic027.
I am rank 27 from 40 procs, running on smic027.
I am rank 28 from 40 procs, running on smic027.
I am rank 29 from 40 procs, running on smic027.
I am rank 30 from 40 procs, running on smic027.
I am rank 31 from 40 procs, running on smic027.
I am rank 32 from 40 procs, running on smic027.
I am rank 14 from 40 procs, running on smic025.
I am rank 15 from 40 procs, running on smic025.
I am rank 16 from 40 procs, running on smic025.
I am rank 17 from 40 procs, running on smic025.
I am rank 18 from 40 procs, running on smic025.
I am rank 19 from 40 procs, running on smic025.
I am rank 0 from 40 procs, running on smic025.
I am rank 1 from 40 procs, running on smic025.
I am rank 2 from 40 procs, running on smic025.
I am rank 3 from 40 procs, running on smic025.
I am rank 4 from 40 procs, running on smic025.
I am rank 5 from 40 procs, running on smic025.
I am rank 6 from 40 procs, running on smic025.
I am rank 7 from 40 procs, running on smic025.
I am rank 8 from 40 procs, running on smic025.
I am rank 9 from 40 procs, running on smic025.
I am rank 10 from 40 procs, running on smic025.
I am rank 11 from 40 procs, running on smic025.
I am rank 12 from 40 procs, running on smic025.
I am rank 13 from 40 procs, running on smic025.
```

Concerning the experiments. Unless you have to propose a specific distribution, I will put the first 20 processes to the first node, the second 20 to the second node and so on. When, they finish I will provide you with the data.

**Comment by mkhoshle** [comment]
Thank you Giannis. good to hear that you will be having the data soon and thanks for the detailed description of what you have done. Let me have a look at your data, we can have another test with the distribution I used in Bridge. I will check that and I will update you soon.

**Comment by mkhoshle** [comment]
I have used the following and I am just using equal number of cores in each node and I used 3 nodes.
Let me know if you have any question.
```mpirun -np $kk -perhost $(($kk/$SLURM_JOB_NUM_NODES)) $SLURM_SUBMIT_DIR/$my_file.py $jj```

**Comment by iparask** [comment]
The data have been uploaded. Please check them. Also, I have a couple of questions for your proposed solution.

1. I cannot find this `perhost` flag. Can you point me to its documentation? 
2. Why do you need to do that? As far as I know you can specify the number of MPI processes per node in your `SBATCH` script or that does not have any effect with a custom installation?

**Comment by mkhoshle** [comment]
Well,
1. Just google it and you will see it or do `mpirun --help` in terminal and you will see it among the options ` Other Hydra options:`.
```
    -v | -verbose                    verbose mode
    -V | -version                    show the version
    -info                            build information
    -print-rank-map                  print rank mapping
    -print-all-exitcodes             print exit codes of all processes
    -iface                           network interface to use
    -help                            show this message
    -perhost <n>                     place consecutive <n> processes on each host
    -ppn <n>                         stand for "process per node"; an alias to -perhost <n>
    -grr <n>                         stand for "group round robin"; an alias to -perhost <n>
```
2. Because in submit script I am changing the number of processes and in every run the number of cores I want in each node is different (In fact, kk is changing).

**Comment by mkhoshle** [comment]
Thanks, Giannis. I looked at the data and you are getting the speed-up for parallel IO. Over the weekend I will plot the results from all clusters on top of each other and update the paper and every one. Also, could you please run the splitting the trajectories (with and without Ga4py) and put them in our shared folder? We need these results from another cluster too.
All the splitted trajectories are in our shared folder `MPI-traj-split`.

**Comment by iparask** [comment]
Hello, I just put the data there. The folders that have a G as a suffix are those with ga4py. As you will see not all node counts are included. This is because the experiments underutilized the requested number of cores and SuperMic is configured to kill those jobs. I am trying to see if that is true and how to fix it.

**Comment by mkhoshle** [comment]
So you mean the results are correct or are not correct? I mean are they good to be added to the paper? 
Also, do you have the results for one core included too? I need them for reference as I said before.

**Comment by iparask** [comment]
I am not sure if the results are correct. It seems that the experiments are under utilizing SuperMic's cores which is violating their policy. Did the plots look ok or not? Is there a chance the execution is not load balanced between the processes or is there time spent not using the cores that dominates the execution? I think these two are the possible reasons for under utilizing the cores, since the partitioning scheme is supposed to mitigate the IO bottleneck.

The single core are in queue. As soon as I get something I will move it to Comet.

**Comment by mkhoshle** [comment]
I do not understand what you are talking about. What do you mean by underutilized the requested number of cores?
Which test case are you talking about? Splitting with GA or without GA?
Are the number of cores you are using equal to the number of trajectory segments? They should be the same. If they are not the same, your runs are not correct.
