### ISSUE TITLE
please clarify paragraph in section on tcomp/tcomm

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#11]
I am not sure what the point of the following is, can you make it clearer? 
https://github.com/hpcanalytics/paper-hpc-py-parallel-mdanalysis/blob/abe577cd0bd0e35eca661e3da165d529e29faeae/tcomm.tex#L15

> Communication is usually not problematic within one node because of the shared memory environment.
> As a result, communication time is not an issue even if the compute to communication ratio is small (Figure \ref{fig:tcomp_tcomm_ratio}, 1-24 cores represent a single compute node on \emph{SDSC Comet}).
> However, beyond a single node, communication overhead becomes a bottleneck and effect of \tcomp/\tcomm becomes very important (Figure \ref{fig:tcomp_tcomm_ratio}, 24-72 cores represent multiple compute nodes on \emph{SDSC Comet}).

Perhaps add values to quantify large/small? 

The figures might show this more clearly if there was a plot correlating the tcomp/tcomm ratio with efficiency, similar to what we have for tcomp/tIO.

**Comment by mkhoshle** [comment]
@orbeckst I edited this section of the paper. Could you please have a look and let me know if it is still not clear?

**Comment by orbeckst** [comment]
It's a bit better; I was looking for more quantitative relationships but we now have this in the appendix and I think it's ok for now.
