### ISSUE TITLE
reformulate paragraph on POSIX IO

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#15]
The paragraph starting on https://github.com/hpcanalytics/paper-hpc-py-parallel-mdanalysis/blob/b3547961520400bfc9a5f2fcb490c105f748b77a/experiments.tex#L364-L369 needs to be rewritten because the sentences are almost verbatim from https://www.nextplatform.com/2017/09/11/whats-bad-posix-io/

**Comment by mkhoshle** [comment]
Corrected. Sorry, it was not supposed to be like that. I think I forgot to modify and work on that part.
