### ISSUE TITLE
Github url provided multiple times

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#17]
The URL to the supplement repo (https://github.com/hpcanalytics/supplement-hpc-py-parallel-mdanalysis) is provided in the text 4 times. 

The occurrences are:
1. Page 4 - Introduction
2. Page 13 - Benchmark Environment
3. Page 16 - Methods
4. Page 27 - Performance Evaluation

I do not think it is needed to be provided this many times. It can easily pointed once and then use a reference.

**Comment by mkhoshle** [comment]
Ok thanks, I corrected it.
