### ISSUE TITLE
HDF5 url in page 11

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#19]
The URL for HDF5 can be moved along with citation number 50.

**Comment by mkhoshle** [comment]
@iparask 49 or 50? Because citation 50 is for Seyler et al.

**Comment by iparask** [comment]
It's respective one. Apparently, when I compile it the citation numbers are a bit different.

**Comment by mkhoshle** [comment]
But these two citations are not the same.

**Comment by iparask** [comment]
That would be 49

**Comment by mkhoshle** [comment]
49 is the pythonhdf5 book the other link refers to the hdf5 website.

**Comment by iparask** [comment]
Ah okay! Then I do not see a need to have the URL in the text. Regardless it can be moved to the book citation, since I do not see a reason not to.

**Comment by mkhoshle** [comment]
Previously it was in the citations, @orbeckst suggested to have it in the text.

**Comment by orbeckst** [comment]
Citation 49

49. Collette A. Python and HDF5. O’Reilly Media, Inc., 1005 Gravenstein Highway North, Sebastopol, CA 95472.; 2014.

is a book so I don't think it is necessary to add a URL to it. 

We have to check the rules for citations for CPC but more often than not, only publications are in the citations and anything else is inline. If this is the case then it is safer to keep the URL in the text anyway.

**Comment by orbeckst** [comment]
If you disagree then we can re-open the issue. Until then I close it without further action.
