### ISSUE TITLE
SuperMIC infos need to be added to the paper

### ISSUE THREAD

**Issue by mkhoshle** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#2]
@iparask Could you please add the info related to MPI-IO runs on SuperMIC to related section of the paper?
I am planning to write the discussions for the related section over the weekend plus I need to add SuperMIC results. And for that, I need to know those info plus I need the results for one core as the reference. 
These info include SuperMIC system features, N_cores per node, Number of cores you have per node in order to overcome IO bottlenecks, etc.
Please have a look at the related sections of the manuscript and add the related info.

**Comment by iparask** [comment]
Added the text with SuperMIC's description. Can you point me to the section that describes the process placement? I could not find it.

**Comment by mkhoshle** [comment]
That section is not added yet. I am waiting for you to provide me with results. 10 days ago you told me that the jobs with one core are running and I think they should not take more than a few hours. Are your results ready or do I need to still wait for you to provide me with results? Are they still running?
What is going on?
What happened to your results? When are you going to have them ready? 
As I said hundreds times before I need them to complete the plots and write the discussions.

**Comment by iparask** [comment]
Hello Mahzad,

```
[iparask@comet-ln3 split_traj]$ pwd
/oasis/projects/nsf/unc100/iparask/GiannisMahzadShareSpace/SuperMic/split_traj
[iparask@comet-ln3 split_traj]$ ls -alh
total 390K
drwxrwsr-x 12 iparask unc100 33K Jun  5 13:11 .
drwxrwsr-x  5 iparask unc100 33K Jun  3 13:26 ..
drwxrwsr-x  2 iparask unc100 33K Jun  5 09:55 1core
drwxrwsr-x  2 iparask unc100 33K Jun  5 12:00 1coreG
drwxrwsr-x  2 iparask unc100 33K Jun  5 13:11 1node
drwxrwsr-x  2 iparask unc100 33K Jun  3 13:26 1nodeG
drwxrwsr-x  2 iparask unc100 33K Jun  3 13:26 2nodes
drwxrwsr-x  2 iparask unc100 33K Jun  3 13:26 2nodesG
drwxrwsr-x  2 iparask unc100 33K Jun  5 13:11 4nodes
drwxrwsr-x  2 iparask unc100 33K Jun  3 13:26 4nodesG
drwxrwsr-x  2 iparask unc100 33K Jun  5 13:11 8nodes
drwxrwsr-x  2 iparask unc100 33K Jun  5 13:11 8nodesG
```
It's all there, I think.

**Comment by mkhoshle** [comment]
Thanks, In the SuperMIC folder you have: may25_2018,  may7_2018,  split_traj. 
I assume split_traj is for splitting the trajectories, 
may25_2018 is MPI-IO for hdf5? 
What is may7_2018 for?

**Comment by mkhoshle** [comment]
Also, how was the rank distribution? 
Did you use N_processes/SLURM_JOB_NUM_NODES? 
I need to know these assumptions for the comparison.

**Comment by iparask** [comment]
may7 is old measurements that did not scale. The other two are correct.

I used 20 processes per node and I submitted on PBS job per node count. So, 20, 40, 80,  and 160 processes for 1, 2,4, and 8 nodes

**Comment by mkhoshle** [comment]
Ok, I see. Thanks.

**Comment by mkhoshle** [comment]
@iparask For parallel IO with HDF5 you are using all number of cores per node. So what has changed that your results were not previously scaling and it is scaling now?

**Comment by iparask** [comment]
Please see the [comment](https://github.com/hpcanalytics/paper-hpc-py-parallel-mdanalysis/issues/1#issuecomment-391159115) in issue #1. That is what changed

**Comment by mkhoshle** [comment]
Can you please add these details to the section (Installing softwares on multi-user HPC systems) of the paper? Just add a subsection in the paper and include these detail. Maybe we need a table for the comparison of these info on all clusters. I will add the ones for other clusters later.

**Comment by iparask** [comment]
Yes. Also the folders with a `G` as suffix under split_traj folder are the ones with GA4py.

**Comment by mkhoshle** [comment]
Yes, I figured that out. Thanks.

**Comment by mkhoshle** [comment]
@iparask It seems to me that the results for Splitting the trajs with GA with 160 cores are somehow mistaken. I think you have the results without GA in that folder instead. Can you please repeat them again? (Only 160 cores)

**Comment by iparask** [comment]
How are they mistaken? I do think I made such a mistake. Regardless, I rerun it and you will see new data in folder `8nodeG`. Folder `8nodesG_jun6` is the old ones. Can you please show me the difference between the two? If it is in the timings, I am not sure if you should discard them without further checks.

**Comment by mkhoshle** [comment]
Ok. Now they are correct. Previously for each repeat, for example, 160 (repeat 1), you had only 6 outputs in data2.txt which seemed to me that you have mistakenly used the non-GA code. 
However, the new results are fine because you have 7 rows for each repeat. 
In the case, without ga I only output 6 parameters, for the ones with GA I output 7 parameters. 
The difference is in the code where we output the results.

**Comment by mkhoshle** [comment]
@iparask  What you have added to manuscripts is not enough and actually not clear. Please address the following questions in the manuscript:

1. What was the problem? (e.g. Rank distribution)
2. How was the problem preventing you from achieving good performance? (Some nodes were busy while the rest were not, or uneven distribution of ranks)
3. How did you overcome the problem? (what can be done to avoid it)

And finally explain what was different that in Comet we did not have this problem, but we had in SuperMIC?
The answers to these questions would be interesting to be added to the paper.
