### ISSUE TITLE
Section 3 is difficult to connect

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#21]
The title of section 3 reads:
```
Molecular Dynamics Analysis Applications
```

One application  is introduced which is RMSD as it is implemented in MDAnalysis, and then has 3 subsections named
```
MPI for Python
Application for Global Arrays
MPI and Parallel HDF5
```

Although I understand that the section wants to introduce the software used, the title is not very helpful.

May I suggest to change the title of the section to `Software Modules Used` or something similar?

**Comment by mkhoshle** [comment]
Yes, that is a good idea. Corrected!
