### ISSUE TITLE
Time to completion vs time to solution

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#23]
I'm a bit confused with time to completion vs time to solution. The text for time to completion says:

```latex
the total time to completion for a single process on $N$ cores is $t_{N}$, as a result 
$t_{\text{RMSD}} + \tcomm \equiv t_{N}$.
```

For time to solution, it says:

```latex
We also recorded the total time to solution $t_{\text{total}}(N)$ with $N$ MPI processes on 
$N$ cores (which is effectively $t_{\text{total}}(N) \approx \max t_{N}$). 
```

I am confused how a single process can run on $N$ cores. The workload is distributed on $N$ cores. not a single process, because we do not use multithreading. I will try to fix it in the text and open a PR with the change.

**Comment by mkhoshle** [comment]
You are right. That was a mistake. Corrected.
