### ISSUE TITLE
Section 3 has one subsection

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#25]
It is not good practice to have a section that has one subsection, which in turn has one subsection.

I suggest that the subsections in section 3 should either be collapsed or section 3 should be merged with section 4 and use the name of section 4.

**Comment by mkhoshle** [comment]
I see. I think I misunderstood what you meant in issue #21.

**Comment by iparask** [comment]
Probably, I also was not very clear. Having any (sub-)section with one (sub-)subsection is generally bad practice. That means that section 3.1 and 3.1.1 should be collapsed.

**Comment by mkhoshle** [comment]
Corrected!

**Comment by orbeckst** [comment]
This looks good to me in the current draft.

The _Root Mean Square Distance (RMSD)_ is still a lone named paragraph – I can live with it, but if anyone feels strongly about it, just remove the heading.

**Comment by iparask** [comment]
To me too!
