### ISSUE TITLE
Discussion about last paragraph subsection 2 related work

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#26]
The last paragraph subsection 2 of the related work reads:
```latex
Although straggler tasks are a common challenge arising in parallel analysis and 
are well-known in the data analysis community (see Section \ref{sec:stragglers}), 
there is, to our knowledge, little discussion about this problem in the biomolecular
simulation community. Our own experience with a MapReduce approach in 
\package{MDAnalysis}~\cite{Khoshlessan:2017ab} suggested that stragglers 
might be a somewhat under-appreciated problem. Therefore, in the present work 
we want to better understand requirements for efficient parallel analysis of 
MD trajectories in \package{MDAnalysis}, but to also provide more general guidance 
that could benefit developments in other libraries inside and outside of the scope of 
analysis of MD simulations.
```
It does not read very well with what precedes it, because as I understand it subsection 2 discusses how others have parallelized MD analysis. I believe it can either go with subsection 1 of section 2 or in the introduction. 

Having said, that this is very well stated and by all means it adds to the paper!

**Comment by mkhoshle** [comment]
But in the other works who have parallelized MD analysis, Stragglers have never been discussed. This is for the first time that we are discussing this in MD community. I believe this is the right place for it to be. Subsection 1, introduces and discusses the straggler problem and how it has been dealt with from a computer science point view. Basically, some remedy for straggler has been suggested. But there is no discussion on its cause and how to cure it. Subsection 2 says that we observed it in our analysis and we have found its causes which have not been studied in the MD community previously. Maybe other works have faced it but never discussed it. But we discussed it and suggested two important performance parameters and strategies to remove it. Does this make sense?

**Comment by mkhoshle** [comment]
@iparask Do you agree with this?

**Comment by iparask** [comment]
I am still not sure. Every time I read this part, I have the same question. I still have not a clear suggestion, that is why I have not followed up yet.

**Comment by orbeckst** [comment]
You can keep thinking about it – this is not going to hold up paper reviewing by the others.

I am waiting for approval on PR #33 and will address #14 in the mean time.
