### ISSUE TITLE
Too much use of *simple* and *obvious*

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#28]
As I'm reading the experiments section, I see that `simple` and `obvious` are used substantially in the text. That makes me ask, if something is simple or obvious how it helps the message of the paper?

I will propose edits soon that remove them, but still it makes me wonder.

**Comment by orbeckst** [comment]
By all means, eradicate as many adjectives as possible. They are generally superfluous in academic writing.

(Btw, by using "significantly" in your statement above, you hit on one of my pet peeves: only use "significantly" if you can establish a statistical significance level. If you feel you need to use something in its place, try "substantially", which has a more diffuse meaning.)

**Comment by iparask** [comment]
I think they are not there any more. I will look at the rest of the paper and remove them.

**Comment by orbeckst** [comment]
Looking fine to me.
