### ISSUE TITLE
Software vs Softwares

### ISSUE THREAD

**Issue by iparask** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#3]
I am not sure if this correct or not, but softwares does not sound very right. Software is an abstract term and its realization can be an executable, API, libraries, tool or stacks.

Do you mind changing softwares to libraries or tools, according to what you want to say!

**Comment by mkhoshle** [comment]
ok, thanks. I will make that correction and will double check with you again.

**Comment by mkhoshle** [comment]
@iparask I corrected them in the text based on what you suggested. Could you please double check that section of the paper and close the issue in case everything looks fine to you?

**Comment by iparask** [comment]
I am closing this ticket since it is being resolved
