### ISSUE TITLE
overbar{t} quantitities need to be defined in section 5.1

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#31]
At some point, overbars were added to t_comp, t_IO, t_comm etc to make the text more consistent but the "overbarred" quantities are not defined (as averages) in Section 5.1.

Add clear definition.

**Comment by orbeckst** [comment]
@mkhoshle @iparask could you please address this issue? Without a definition it makes the paper hard to read and I would like this fixed before @shantenujha @foxsden have to read it.

**Comment by iparask** [comment]
I made a commit in the `proposed_edits/experiments` branch trying to address this issue. @orbeckst can you check and let me know?

**Comment by orbeckst** [comment]
Your edit in PR #30 fixes this issue.

(Now I realize that this information is already in Table 3 but for readability it has to be in the main text.)
