### ISSUE TITLE
Question: MPI versions for mpi4py and GA?

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#35]
Does GA use the same MPI as other experiments? Different MPI versions do handle intra-node communications in different ways and that can have a big effect.

What are the exact MPI versions that we are using, for _Comet, Bridges, SuperMIC_?

- for mpi4py ("MPI" in Table 5)
- for GA/GA4py (see #32) ("GA in Table 5")
- for PyHDF5 and mpi ("MPI PHDF5" in Table 5)

In particular, do we use the same MPI versions with "MPI only" (eg Fig 1)  and with "GA" (eg Fig 3), and if so, which version? Table 2 in the draft lists "OpenMPI 1.10.7" but it's not clear if we used it consistently. [Installation_Guide/Global_Array.sh](https://github.com/hpcanalytics/supplement-hpc-py-parallel-mdanalysis/blob/master/Installation_Guide/Global_Array.sh) suggests that GA was built with 1.10.7 but what did we use mpi4py with?

@mkhoshle could you please fill in the table below with the MPI version information and show how you obtained this version information? Thanks!

| machine  | MPI | GA | MPI PHDF5 |
|----------|--------|----|--------| 
| Comet    |        |    |  |
| Bridges  |        |    |     |
| SuperMIC |        |    |     |

**Comment by mkhoshle** [comment]
@orbeckst I have used the same MPI version for everything. It has always been the same and consistent. This is mentioned in the section `software`. Do we need to add this table when MPI version has been the same everywhere? I used 1.10.7 on both Comet and Bridge and I told @iparask to use the same version as well. @iparask could you please confirm?

**Comment by iparask** [comment]
Hello @orbeckst , @mkhoshle,

The experiments on SuperMic were executed with OpenMPI 1.10.7:
```
[iparaske@smic1 ~]$ which mpirun
/work/iparaske/MahzadInstallations/openmpi-1.10.7-install/bin/mpirun
[iparaske@smic1 ~]$ mpirun --version
mpirun (Open MPI) 1.10.7

Report bugs to http://www.open-mpi.org/community/help/
```

**Comment by orbeckst** [comment]
Thanks everyone, just making doubly-sure because different MPI versions can be behave differently.
