### ISSUE TITLE
data points cut off in figures

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#36]
## Extend range of figures
In Figure 1c, 4c, 5a, 6c, 7a, 7c, 8a, 8b, 8c, A10c, A11c, A13a, C15a (scaling of different components) and A12a-c (parallel efficiency) the last data point(s) are cut off at the edge and the error bars are not visible or data points are missing completely. (See the PDF [main.pdf @ 1682d9723743d0cf31b7c7b6e454ca1c8278d94d](https://github.com/hpcanalytics/paper-hpc-py-parallel-mdanalysis/blob/1682d9723743d0cf31b7c7b6e454ca1c8278d94d/main.pdf) for figure references.)

Please extend the x-axis out to 100 = 1e2  to clearly show the last datapoint; extend the y-axis as much as necessary to show error bars and any other graphs (e.g., in 1c, the open_trajectory line is partially cut off so extend the y axis down to 1e-1 so that the graph is clearly visible).

For some of the graphs (such as 5a), the above limits are not correct – simply add at least one decade on the log plot to make sure that the whole datapoint and its error bar is inside the graph and that the tick mark appears on the x-axis. If the next major tick mark  is 3 ticks or less away (such as 1e2 for 72) then include it to make the x-axis easier to read.

- [x] scaling components Comet (1c)
- [x] scaling components Comet (GA) (4c)
- [x] scaling components Comet (splitting) (5a)
- [x] scaling components Comet (HDF5) (6c)
- [x] scaling components tcomp and tIO Comet/SuperMic (GA) (7a) 
- [x] scaling components tcomp and tIO Comet/SuperMic (GA) (7c) (*data are missing*)
- [x] scaling total,  Comet/Bridges/SuperMic (HDF5) (8a) (*data are missing*)
- [x] speed up,  Comet/Bridges/SuperMic (HDF5) (8b) (*data are missing*)
- [x] scaling tcomp and tIO,  Comet/Bridges/SuperMic (HDF5) (8c) (*data are missing*)
- [x] scaling components Bridges (A10c)
- [x] scaling components SuperMic (A11c) (*data are missing*)
- [x] scaling components SuperMic  (GA) (A13a)
- [x] scaling components Comet (ChainReader) (C15a) (*data are missing*)

## Error bars on Opening_trajectory?
While looking through the scaling figures I also noticed that some of the *Opening trajectory* graphs (such as the one in 1c and 4c) show rather large changes with Nprocessors but the error bars are not visible and are presumably tiny. I would have expected to see some variance (which is also implied by the per-rank breakdown in Fig 1d).

What values do the standard errors on trajectory_opening have over the 5 repeats?

Please check that these graphs are plotted with error bars.

**Comment by mkhoshle** [comment]
@orbeckst I addressed this issue and pushed my commit. And you are right, it seems that some of the error bars were missing. I have added them and now they are correct. For some cases, they are large and previously it was missing.

**Comment by mkhoshle** [comment]
Also for figure 8b, I did not extend x-axis to 200 in order to show exactly how the scaling differs between different cases. When I extend this axis it is really hard to see this clearly in (0,100) region.

**Comment by orbeckst** [comment]
Thanks!
