### ISSUE TITLE
Performance bottleneck vs Scalability Bottleneck

### ISSUE THREAD

**Issue by mkhoshle** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#37]
@orbeckst  I do not understand the difference between performance bottleneck vs scalability Bottleneck mentioned in commit [d82a924](https://github.com/hpcanalytics/paper-hpc-py-parallel-mdanalysis/commit/d82a92478855755db4ecb71282091783cd770715). Performance and scalability are related. Performance is defined based on efficiency and scalability is defined based on speed-up.  Speed-up and efficiency (and as a result performance) are related to each other. Why do you think these are different?

**Comment by mkhoshle** [comment]
I think we should use scaling performance behaviors and we have done strong and weak scaling diagnostics. So I do not think using performance should be a problem.

**Comment by orbeckst** [comment]
We had a consensus among the PIs to change it in the way written.
