### ISSUE TITLE
data files and plotting code

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#38]
For each individual plot we want to have the **data** and the **Python code** that generated the figure. There is a directory for each subfigure under [data](https://github.com/hpcanalytics/paper-hpc-py-parallel-mdanalysis/tree/master/data). For example, for Figure 2a, the directory is `data/Fig2/a`.

*It should be possible to re-generate the figure in the paper from the data and code in each figure sub directory. Each subdirectory should be largely self contained.*

Ideally, all data are in individual CSV files and the CSV files are read by the plotting code. Other solutions are also ok, as long as one can generate each plot in its own directory. Multiple data files can also be put in a single directory. Data files can be copied and duplicated over multiple directories. 

Jupyter notebooks are ok but the notebook should be cleaned up so that it just plots the one figure so that there is no confusion about what is plotted and how to do it.

**Comment by mkhoshle** [comment]
@orbeckst Are you waiting for this for the submission of the paper?

**Comment by orbeckst** [comment]
The data should be added before submission to a journal.

**Comment by mkhoshle** [comment]
Ok, I am working on them.

**Comment by mkhoshle** [comment]
@orbeckst I added all the data and postprocessing codes to the repository and made a pull request.
