### ISSUE TITLE
math latex formatting

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#6]
subscripts and superscripts such as "frame", "I/O", "frames", "comp" that are not variables should be set in roman type, using `\text{}`, e.g., `N_\text{frames}`.

Sections where I noticed (there might be others)

- [x] methods 5.1 
- [x] results 6.5
- [x] appendix captions

**Comment by mkhoshle** [comment]
Corrected!
