### ISSUE TITLE
comparison of parallel efficiency figure for SuperMIC and Bridges

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#7]
Figure B.11 is great for a higher-level comparison. 
> Figure B.11: Comparison of the parallel efficiency between different test cases on SDSC Comet. Five repeats are performed to collect statistics and error bars show standard deviation with respect to mean.

It would be good to have the same figure for all three resources so that we can show more clearly that we get very similar results on all machines

- [x] Comet
- [x] Bridges
- [x] SuperMIC

Can you plot the data that you have for Bridges and SuperMIC in the same way as for Comet (E(N)) and make Fig B.11 a three-panel figure.

**Comment by orbeckst** [comment]
Please also see comment in 2a31f218621b048d8b54e69360b9f76fcfa82c22 – would also be good to have a figure like 1c for Bridges and SuperMIC.

**Comment by mkhoshle** [comment]
@orbeckst Are these figures really necessary? We have a section called cluster comparison, and in that section, we show the comparison for three test cases. And the comparison shows that all the results are similar. I believe the paper is getting too long. There is no point on adding a plot that carries no additional or new message I think.

In addition, I do not have such a result. If you want this we need to ask @iparask to run RMSD, RMSD Ga, chain-reader and chain-reader-ga. On SuperMIC I only received Parallel-HDF5, Splitting the trajectories Ga and No GA. If you still think that they are necessary I can run those cases on bridges and as soon as I get them from @iparask for SuperMIC I will add them.

**Comment by orbeckst** [comment]
> We have a section called cluster comparison, and in that section, we show the comparison for three test cases. And the comparison shows that all the results are similar.

The cluster comparison section is certainly good – nice work!

From what you said above and Table 5 I see that we have the following (x in the table; I omitted the ChainReader simulations, which we only have on Comet):

**gather**|**File access**|**Comet**|**Bridges**|**SuperMIC**
:-----:|:-----:|:-----:|:-----:|:-----:
MPI|single|x| TODO | TODO 
GA|single|x| | 
MPI|splitting|x| |x
GA|splitting|x| |x
MPI|PHDF5|x|x|x

I agree that we do not have to run *all* the simulations on all clusters; the ones that we have should be sufficient, with the following exception:  I'd really like to see stragglers on Bridges and SuperMIC ("TODO" in the table) and plotted as in Fig 1 (as two additional figures in the Appendix)  so that we can also clearly show that there a straggler problems on Bridges and SuperMIC: This will make the logic of the paper much stronger:

1. show that we have stragglers on Comet
2. show that we understand where the stragglers come from and how to deal with them (on Comet)
3. show that stragglers are a problem elsewhere (Bridges, SuperMIC), i.e., this is not specific to a single supercomputer
4. show that our solutions generalize to other systems (Bridges, SuperMIC) – we don't have to do everything again but enough to show that our benchmarks behave in a comparable manner.

## Additional simulations

- [x] @mkhoshle can you please run 5 repeats of the RMSD/single/MPI on **Bridges** ?
- [ ] @iparask can you please run 5 repeats of the RMSD/single/MPI on **SuperMIC** ?

## New figures

We will then have data for the following figures
- appendix: like Fig 1 but for SuperMIC (shows stragglers)
- appendix: like Fig 1 but for Bridges (shows stragglers)
- appendix: update B.11 to be a 3-panel figure: 
  - (A): efficiency for Comet (current B.11)
  - (B): efficiency for SuperMIC (like B.11A, but with the data that we have for SuperMIC)
  - (C): efficiency for Bridges (like B.11A, but with the data that we have for Bridges)

**Comment by mkhoshle** [comment]
@orbeckst Your grant is overdrawn on Bridges RM.  In order to be able to run on the RM partition, you  have to ask for a supplement or transfer of units. Please let me know when you do this.

**Comment by iparask** [comment]
Hello @orbeckst , @mkhoshle,

sorry for the late reply. I will try and run them again. What is needed on SuperMic. Can you point me where the scripts to run the additional experiments are? 

Thank you,
Giannis

**Comment by mkhoshle** [comment]
Hello @iparask, @orbeckst has mentioned [here](https://github.com/hpcanalytics/paper-hpc-py-parallel-mdanalysis/issues/7#issuecomment-441861051) what is necessary and here is the path to files. `/oasis/projects/nsf/unc100/iparask/GiannisMahzadShareSpace/MPI-RMSD`.

**Comment by iparask** [comment]
Alright!

**Comment by orbeckst** [comment]
Ok, will do.

**Comment by orbeckst** [comment]
I submitted the request.

**Comment by mkhoshle** [comment]
@orbeckst In the meantime, if you can provide your comments for the rest of the paper, it will be great.

**Comment by orbeckst** [comment]
We should have SUs on bridges again. (This was really fast!!) Please try. 

Awarded Resources: LSU Cluster (superMIC): -15,000.0 SUs
PSC Regular Memory (Bridges): 46,000.0 SUs
TACC Dell/Intel Knights Landing, Skylake System (Stampede2): -1,495.0 Node Hours



> Am Nov 29, 2018 um 16:22 schrieb Oliver Beckstein <orbeckst@gmail.com>:
> 
> Ok, will do.
>

**Comment by orbeckst** [comment]
Will try, traveling at the moment. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by mkhoshle** [comment]
I do not see anything in my XSEDE account and I get the same error when I try to submit a new job.

**Comment by orbeckst** [comment]
I checked my Xsede Portal page and there is listed  for Bridges *Remaining: 34374.1 of 305608.0 SUs*. Maybe it takes a day for it to become active again? Can you please try again tomorrow and if it still doesn't work, please contact the [Xsede helpdesk](https://portal.xsede.org/group/xup/help-desk) (and cc me so that I can add context to the request if necessary). Thanks.

**Comment by mkhoshle** [comment]
@orbeckst I submitted my job. Thanks.

**Comment by mkhoshle** [comment]
@iparask Do you have your results ready from SuperMIC?

**Comment by iparask** [comment]
I am working on it. I will update as soon as I have the results.

**Comment by iparask** [comment]
1 core, 1 node and 2 nodes results are in `/oasis/projects/nsf/unc100/iparask/GiannisMahzadShareSpace/MPI-RMSD/SuperMic` on Comet. 

The 4 node and 8 node failed with a bad crc error. This usually originates from Numpy, I will check and report again.

**Comment by mkhoshle** [comment]
@iparask Thanks for the update. let me know when the rest are ready.

**Comment by orbeckst** [comment]
@mkhoshle thanks for the updated Bridges figures in the draft. These results look much more reasonable.

In Fig B12 we are now comparing Comet, Bridges (and SuperMic once we have the data). It would be clearer if the same line colors were used for the same computational experiments on the three machines so that it is easy to visually compare. 

It will also allow us to just have a single legend. (A figure with three panels of the same size and the legend underneath.)

Something like
- red: MPI
- blue:  GA
- gray: MPI, trajectory splitting
- black: GA, trajectory splitting
- pink: MPI, parallel I/O [use for "best result", i.e., for Bridges Np/N]
  - pink, dashed: MPI, parallel I/O [8 cores/node]
  - pink, dotted: MPI, parallel I/O [14 cores/node]
  - pink, dash-dotted: MPI, parallel I/O [28 cores/node]
- yellow: MPI ChainReader
- green: GA ChainReader

The idea would be to have the same colors for the same experiments, with variations in line style to indicate, for instance, different core numbers per node. The colors above are only suggestions, perhaps you can come up with something that looks better. 

We can also leave out "RMSD" from the label because we only do RMSD runs.

**Comment by iparask** [comment]
Hello, I am still facing CRC issues when I execute with 4 and 8 nodes and I am still looking into it.

**Comment by mkhoshle** [comment]
@iparask What is crc error? Ok, thanks for letting me know.

**Comment by iparask** [comment]
Numpy from time to time gives a `Bad-CRC` error for some files. Fortunately, it was something that a reinstall of the package resolved. I uploaded 4 and 8 nodes

**Comment by mkhoshle** [comment]
Ok, thanks.

**Comment by mkhoshle** [comment]
Corrected!

**Comment by orbeckst** [comment]
Do we have the SuperMIC data for MPI Single 1x RMSD run and processed?

- [x] The current draft does not contain an appendix figure B12c for SuperMIC (see also https://github.com/hpcanalytics/paper-hpc-py-parallel-mdanalysis/issues/7#issuecomment-446032785). 
- [x] Appendix figure that shows stragglers (like current Fig 1 for Comet and Fig B.11 for Bridges).

Could you please add them (or push your local commits if you already have this)? Thanks!

**Comment by mkhoshle** [comment]
@orbeckst I updated it!

**Comment by orbeckst** [comment]
Excellent,  looking good. Thanks.
