### ISSUE TITLE
update figures 2b, c with measured load ratios

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#8]
I re-computed the tcomp/tIO ratios in Table 4

workload | tcomp | tIO | measured | theory
-- | -- | -- | -- | --
1 | 226 | 791 | 0.286 |  
40 | 8655 | 791 | 10.942 | 11.429
70 | 15148 | 791 | 19.150 | 20.000
100 | 21639 | 791 | 27.357 | 28.571

where _measured_ is the ratio of  tcomp/tIO and _theory_ comes from the analysis in the paper, namely that for the XxRMSD task the tcomp/tIO ratio should be X times the 1x ratio. In the draft I rounded to two significant figures, i.e.,

workload | tcomp | tIO | measured | theory
-- | -- | -- | -- | --
1 | 226 | 791 | 0.29 |  
40 | 8655 | 791 | 11 | 11
70 | 15148 | 791 | 19 | 20
100 | 21639 | 791 | 27 | 29

The draft has 0.3 (1x), 12 (40x), 21 (70x), 30 (100x). I think these numbers come from the theoretical approach with 0.3 as the basis. (Using 0.29 gives better agreement between measured and experimental.)

- [x] The graphs in Figure 2b and 2c need to be redrawn with the experimental ratios so that everything is consistent (instead of the rounded theoretical ratios).
- [x] Text need to be changed.

**Comment by mkhoshle** [comment]
Corrected.
