### ISSUE TITLE
splitting benchmark table: 196 or 192 cores?

### ISSUE THREAD

**Issue by orbeckst** [hpcanalytics/paper-hpc-py-parallel-mdanalysis#9]
Table A.6 currently looks like the following (I added nodes, scaling and efficiency):

N_seg | Np | nodes | time | S | E
-- | -- | -- | -- | -- | --
24 | 24 | 1 | 89.92 | 1.0 | 1.00
48 | 48 | 2 | 46.79 | 1.9 | 0.96
72 | 72 | 3 | 33.7 | 2.7 | 0.89
96 | 96 | 4 | 25.12 | 3.6 | 0.89
144 | 144 | 6 | 43.7 | 2.1 | 0.34
196 | 196 | 8.16666666666667 | 13.49 | 6.7 | 0.82

- [ ] However, I don't think 196 cores is correct. @mkhoshle should it be 192 for 8 nodes?
- [ ] Does the table below look ok?

I _think_ the table _should_ be 

N_seg | Np | nodes | time | S | E
-- | -- | -- | -- | -- | --
24 | 24 | 1 | 89.92 | 1.0 | 1.00
48 | 48 | 2 | 46.79 | 1.9 | 0.96
72 | 72 | 3 | 33.7 | 2.7 | 0.89
96 | 96 | 4 | 25.12 | 3.6 | 0.89
144 | 144 | 6 | 43.7 | 2.1 | 0.34
192 | 192 | 8 | 13.49 | 6.7 | 0.83

**Comment by orbeckst** [comment]
@mkhoshle could you please have a quick look at this issue, I really only need to know if 192 or 196 is correct.

I have not quite finished the draft but will do the Conclusions #12 tomorrow and then send a copy to the collaborators for comments. If you can push any updates that you have by tomorrow ~5pm then I will be able to include them (of course, everyone will be able to look at the repo but it can be inconvenient having to chase the latest draft). If you need more time then we can also wait.

**Comment by mkhoshle** [comment]
@orbeckst 196 IS WRONG and 192 is correct which corresponds to 8 nodes on Comet.

**Comment by mkhoshle** [comment]
I am working on the draft and will push my commits. Please wait till tomorrow morning and I will try to finish my comments.

**Comment by mkhoshle** [comment]
@orbeckst I think it is a good idea to add Speed up and Efficiency to the table. Overall, looks fine to me.

**Comment by orbeckst** [comment]
Thanks. 

--
Oliver Beckstein
email: orbeckst@gmail.com

**Comment by orbeckst** [comment]
Ok, will do. 

--
Oliver Beckstein
email: orbeckst@gmail.com
